In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2=np.arange(10,19).reshape(3,3)
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [6]:
SUMARRAY=arr+arr2
SUMARRAY

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [7]:
diff_arr=arr-arr2
diff_arr

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [8]:
mul_arr=arr*arr2
mul_arr

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

**for proper matrix multiplication use (@) or use np.dot()**

In [9]:
mul_arr=arr@arr2
mul_arr

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

**more matrix opertion**

In [10]:
matrix=np.array([[2,3,-1],[1,2,1],[5,4,-1]])
matrix

array([[ 2,  3, -1],
       [ 1,  2,  1],
       [ 5,  4, -1]])

In [11]:
#transpose matrix.T
matrix.T


array([[ 2,  1,  5],
       [ 3,  2,  4],
       [-1,  1, -1]])

In [12]:
#METHOD 2
transposed= np.transpose(matrix)
transposed

array([[ 2,  1,  5],
       [ 3,  2,  4],
       [-1,  1, -1]])

In [13]:
#Determinant
#firstly import linear algebra
from numpy import linalg

In [14]:
d=linalg.det(matrix)
d

np.float64(11.999999999999995)

In [15]:
#to round them
np.around(d,2)

np.float64(12.0)

**norm(to find the distance between to points)**

In [16]:
arr=np.array([6,8])
print(linalg.norm(arr))

10.0


**dot product**

In [20]:
vector1=np.array([4,0])
vector2=np.array([0,3])

In [21]:
dot_product=np.dot(vector1,vector2)
dot_product

np.int64(0)

In [22]:
norm1=linalg.norm(vector1)
norm2=linalg.norm(vector2)
print(norm1)
print(norm2)

4.0
3.0


**solve linear equation**

#BROADCASTING

In [23]:
matrix=np.arange(1,16).reshape(3,-1)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
vector=np.array([10,20,30,40,50])
vector

array([10, 20, 30, 40, 50])

In [25]:
matrix+vector

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60],
       [21, 32, 43, 54, 65]])