**numpy**

In [2]:
import numpy as np


Making array with the help of numpy

In [3]:
arr=[10,20,30,40,50]
print(arr)
print(type(arr))


[10, 20, 30, 40, 50]
<class 'list'>


In [4]:
a = np.array(arr)
print(a)
print(type(a))


[10 20 30 40 50]
<class 'numpy.ndarray'>


In [5]:
arr=np.array(range(5))
print(arr)

[0 1 2 3 4]


**arange function**

In [6]:
arr=np.arange(10,101,10)
print(arr)
print(type(arr))

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


In [7]:
arr=np.arange(0,101,2)
print(arr)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [8]:
arr=np.arange(1,100,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [9]:
arr=np.arange(5,51,5)
print(arr)
print(type(arr))

[ 5 10 15 20 25 30 35 40 45 50]
<class 'numpy.ndarray'>


**2D array**

In [10]:
arr=[[10,20,30],[40,50,60,],[70,80,90]]
print(arr)
print(type(arr))

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]
<class 'list'>


In [11]:
arr_2d=np.array(arr)
print(arr_2d)
print(type(arr_2d))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>


**To check dimensions of array use (ndim)**

In [12]:
arr_2d.ndim

2

**TO know the shape of array usev (shape)**

In [13]:
arr_2d.shape

(3, 3)

**TO know thw how much elements array have use {size}**

In [14]:
arr_2d.size

9

**if you want to know the data type with how much bits it stored use {dtype}**

In [15]:
arr_2d.dtype

dtype('int64')

now we impliment 2D array

In [16]:
arr_2d=np.arange(1,13,1).reshape(3,4)
print(arr_2d)
print(type(arr_2d))
print(arr_2d.ndim)
print(arr_2d.size)
print(arr_2d.shape)
print(arr_2d.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
2
12
(3, 4)
int64


In [17]:
arr_2d=np.arange(5,46,5).reshape(3,3)
print(arr_2d)


[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


**3D matrix**

In [18]:
import numpy as np
arr_3d= np.arange(1,19,1).reshape(2,3,3)
print(arr_3d)
print(type(arr_3d))
print(arr_3d.ndim)
print(arr_3d.shape)
print(arr_3d.size)
print(arr_3d.dtype)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'>
3
(2, 3, 3)
18
int64


In [19]:
arr_3d=np.arange(1,37,1).reshape(3,3,4)
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


**4D ARRAY**

In [20]:
arr_4d=np.arange(1,73,1).reshape(2,3,4,3)
print(arr_4d)
print(arr_4d[0][2][2][1])

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]
   [19 20 21]
   [22 23 24]]

  [[25 26 27]
   [28 29 30]
   [31 32 33]
   [34 35 36]]]


 [[[37 38 39]
   [40 41 42]
   [43 44 45]
   [46 47 48]]

  [[49 50 51]
   [52 53 54]
   [55 56 57]
   [58 59 60]]

  [[61 62 63]
   [64 65 66]
   [67 68 69]
   [70 71 72]]]]
32


**zeros**

**for making zeros array**

In [21]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [22]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
arr=np.zeros(((2,3,3)))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [24]:
arr=np.zeros((((2,3,4,3))))
print(arr)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


**ones**

**For making 1 array means all elements are 1**

In [25]:
arr=np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [26]:
arr=np.ones((10,10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [27]:
arr=np.ones(((2,3,4)))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
(2, 3, 4)
24
float64


#identity matrix

In [28]:
arr= np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
arr=np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**eye function**

**we are using eye fun bcoz its works same as identity matrix but  identity matrix is square matrix and it is not possible to make (3,4) matrix that's why we use eye function**

In [30]:
arr=np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [31]:
arr=np.eye(4,8)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


In [32]:
arr=np.eye(4,8,2)
print(arr)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]


**Diagonal matrix(diag)**

In [33]:
arr=np.diag((5,5,5,5))
print(arr)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


In [34]:
arr=np.diag((1,2,3))
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


**Full function(it is used when you want to make any matrix with any specific num )**

In [35]:
arr=np.full((3,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [36]:
arr=np.full((5,5),-1)
print(arr)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


**linspace(it is used to generate liniarly spaced elements generation means if you want to divide any array elements in equal parts ypou used that)**

In [37]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [38]:
arr=np.linspace(0,15,3)
print(arr)

[ 0.   7.5 15. ]


#9th March class

In [39]:
import numpy as np

**TO know how much time it takes**

In [40]:
%%time
pythonlist=list(range(100))
for i in range(len(pythonlist)):
  print(pythonlist[i])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
CPU times: user 1.1 ms, sys: 13 µs, total: 1.11 ms
Wall time: 1.05 ms


In [41]:
%%time
my_array=np.arange(100)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
CPU times: user 4.75 ms, sys: 0 ns, total: 4.75 ms
Wall time: 8.11 ms


**Working with vectors**

In [42]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print(type(arr1),type(arr2))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [43]:
arr3=arr1+arr2
arr3

array([11, 22, 33, 44, 55])

In [44]:
arr3=arr1-arr2
arr3

array([ -9, -18, -27, -36, -45])

In [45]:
arr3=arr2/arr1
arr3

array([10., 10., 10., 10., 10.])

In [46]:
arr3=arr1*arr2
arr3

array([ 10,  40,  90, 160, 250])

In [47]:
arr1

array([1, 2, 3, 4, 5])

In [48]:
arr1[3]

np.int64(4)

In [49]:
arr=np.array([10,30,-120,40,50])
print(arr)

[  10   30 -120   40   50]


In [50]:
arr.ndim

1

In [51]:
arr.size

5

In [52]:
arr.shape

(5,)

In [53]:
arr.dtype

dtype('int64')

**TO decide data type**

In [54]:
arr=np.array([10,20,-128,127,50],dtype="int8")
print(arr)

[  10   20 -128  127   50]


In [55]:
arr.dtype

dtype('int8')

In [56]:
arr=np.array([1.1,3,4],dtype="float32")
arr.dtype

dtype('float32')

**Slicing**

In [57]:
arr=np.arange(0,13,1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
arr[4:10:1]


array([4, 5, 6, 7, 8, 9])

In [59]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10, 12])

In [60]:
arr[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [61]:
arr[7:2:-1]

array([7, 6, 5, 4, 3])

In [62]:
#arr[start:end:inc] postive
arr[3:10:2]


array([3, 5, 7, 9])

In [63]:
arr[12:6:-1]
#negative

array([12, 11, 10,  9,  8,  7])

In [64]:
#reversing
arr[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

 **viwe(Shallow copy) vs copy(deep copy- in place)**

In [67]:
#viwe
arr=np.array([30,40,50,60,70])
print(arr)

[30 40 50 60 70]


In [68]:
new_arr=arr
print(new_arr)

[30 40 50 60 70]


In [71]:
new_arr[0]=100
new_arr

array([100,  40,  50,  60,  70])

In [72]:
arr

array([100,  40,  50,  60,  70])

In [ ]:
#copy

In [75]:
new_array=arr.copy()
new_array

array([100,  40,  50,  60,  70])

In [78]:
new_array[3]=300
new_array

array([100,  40,  50, 300,  70])

In [79]:
arr

array([100,  40,  50,  60,  70])

#sorting

In [80]:
arr=np.array([5,3,2,4,1])
arr.sort()

In [81]:
arr

array([1, 2, 3, 4, 5])

In [82]:
arr=np.array([2,6,5,4,1])
sorted_array=np.sort(arr)
print(sorted_array)
print(arr)

[1 2 4 5 6]
[2 6 5 4 1]


In [85]:
arr=np.array([-1,3,-5,6,-7,4])
arr.sort(kind="mergesort")


In [86]:
arr

array([-7, -5, -1,  3,  4,  6])

#Aggregate functins (min,max,avg,count ect)

In [87]:
#sum
arr=np.array([5,3,7,8,9])
sumarray=np.sum(arr)
print((sumarray))

32


In [89]:
#mean
arr=np.array([10,50,20,30,40])
avgarray=np.mean(arr)
print(avgarray)

30.0


In [90]:
#median
arr=np.array([10,20,30,40,50,60])
med=np.median(arr)
print(med)

35.0


In [91]:
arr=np.array([10,20,30,40,50,60])
sd=np.std(arr)
print(sd)

17.07825127659933


In [92]:
arr=np.array([10,20,30,40,50,60])
v=np.var(arr)
print(v)

291.6666666666667


In [94]:
#product
arr=np.array([10,20,30])
product=np.prod(arr)
print(product)

6000


In [95]:
#max / min
arr=np.array([10,20,30,40])
print("max",np.max(arr))
print("min",np.min(arr))

max 40
min 10


In [97]:
#arg max arg min it provide value index of max and min value
arr=np.array([10,20,30,40])
print("argmax",np.argmax(arr))
print("argmin",np.argmin(arr))

argmax 3
argmin 0
